---
# =============================================================================
# НАСТРОЙКА JWT АУТЕНТИФИКАЦИИ ДЛЯ SLURM
# =============================================================================
- name: "Проверка установки libjwt"
  package_facts:
    manager: "auto"
- name: "Валидация установки JWT библиотек"
  assert:
    that:
    - "'libjwt-dev' in ansible_facts.packages or 'libjwt0' in ansible_facts.packages"
    fail_msg: "libjwt не установлен. Требуется для JWT поддержки."
    success_msg: "libjwt установлен и готов к использованию"
  tags:
  - jwt
  - validation
- name: "Создание директории для JWT ключей"
  file:
    path: /etc/slurm/jwt
    state: directory
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0700'
  tags:
  - jwt
  - security
- name: "Проверка существования JWT ключа"
  stat:
    path: "{{jwt_options.key_file}}"
  register: jwt_key_exists
  tags:
  - jwt
- name: "Генерация JWT ключа (если не существует)"
  shell: |
    openssl rand -base64 32 > {{jwt_options.key_file}}
  when: not jwt_key_exists.stat.exists
  tags:
  - jwt
  - security
- name: "Установка правильных прав на JWT ключ"
  file:
    path: "{{jwt_options.key_file}}"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0600'
  tags:
  - jwt
  - security
- name: "Создание JWKS файла для ротации ключей"
  template:
    src: slurm.jwks.j2
    dest: "{{jwt_options.jwks_file}}"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0600'
    backup: true
  tags:
  - jwt
  - config
- name: "Создание скрипта для генерации JWT токенов"
  template:
    src: jwt_generator.py.j2
    dest: /usr/local/bin/slurm_jwt_generator.py
    owner: root
    group: root
    mode: '0755'
  tags:
  - jwt
  - tools
- name: "Создание скрипта для валидации JWT токенов"
  template:
    src: jwt_validator.py.j2
    dest: /usr/local/bin/slurm_jwt_validator.py
    owner: root
    group: root
    mode: '0755'
  tags:
  - jwt
  - tools
- name: "Создание конфигурационного файла для JWT"
  copy:
    dest: /etc/slurm/jwt.conf
    content: |
      # Slurm JWT Configuration
      # Generated by Ansible
      # JWT Key file path
      JWT_KEY_FILE={{jwt_options.key_file}}
      # JWKS file path (for key rotation)
      JWKS_FILE={{jwt_options.jwks_file}}
      # JWT Algorithm
      JWT_ALGORITHM={{jwt_options.algorithm}}
      # Default token expiration (in seconds)
      DEFAULT_EXPIRY=3600
      # Maximum token expiration (in seconds)
      MAX_EXPIRY=86400
      # Issuer identification
      JWT_ISSUER={{slurmctld_options.cluster_name}}
      # Audience (who can use these tokens)
      JWT_AUDIENCE=slurm-cluster
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0600'
  tags:
  - jwt
  - config
- name: "Тестирование генерации JWT токена"
  shell: |
    export JWT_KEY_FILE={{jwt_options.key_file}}
    python3 /usr/local/bin/slurm_jwt_generator.py --user test --expiry 3600
  register: jwt_test_generation
  failed_when: jwt_test_generation.rc != 0
  changed_when: false
  tags:
  - jwt
  - validation
- name: "Тестирование валидации JWT токена"
  shell: |
    export JWT_KEY_FILE={{jwt_options.key_file}}
    TOKEN=$(python3 /usr/local/bin/slurm_jwt_generator.py --user test --expiry 3600)
    echo $TOKEN | python3 /usr/local/bin/slurm_jwt_validator.py
  register: jwt_test_validation
  failed_when: jwt_test_validation.rc != 0
  changed_when: false
  tags:
  - jwt
  - validation
- name: "Создание примера использования JWT"
  copy:
    dest: /etc/slurm/jwt_examples.sh
    content: |
      #!/bin/bash
      # JWT Examples for Slurm
      # Set environment
      export JWT_KEY_FILE={{jwt_options.key_file}}
      echo "=== Slurm JWT Examples ==="
      echo
      # Generate token for user
      echo "1. Generate token for user 'admin' (1 hour):"
      python3 /usr/local/bin/slurm_jwt_generator.py --user admin --expiry 3600
      echo
      # Generate token for service
      echo "2. Generate token for service (24 hours):"
      python3 /usr/local/bin/slurm_jwt_generator.py --user slurm-service --expiry 86400
      echo
      # Test scontrol with JWT
      echo "3. Test scontrol with JWT:"
      TOKEN=$(python3 /usr/local/bin/slurm_jwt_generator.py --user admin --expiry 3600)
      export SLURM_JWT=$TOKEN
      {{slurm_prefix}}/bin/scontrol ping
      echo
      echo "=== End of Examples ==="
    owner: root
    group: root
    mode: '0755'
  tags:
  - jwt
  - documentation
- name: "Создание системного пользователя для JWT сервиса"
  user:
    name: slurm-jwt
    system: true
    shell: /bin/false
    home: /var/lib/slurm-jwt
    create_home: true
    groups: "{{slurm_group}}"
    state: present
  tags:
  - jwt
  - users
- name: "Предоставление доступа к JWT ключам для сервисного пользователя"
  acl:
    path: "{{jwt_options.key_file}}"
    entity: slurm-jwt
    etype: user
    permissions: r
    state: present
  tags:
  - jwt
  - security
- name: "Создание логротейт конфигурации для JWT логов"
  copy:
    dest: /etc/logrotate.d/slurm-jwt
    content: |
      /var/log/slurm/jwt.log {
          daily
          missingok
          rotate 30
          compress
          delaycompress
          notifempty
          create 0640 {{slurm_user}} {{slurm_group}}
   }
    owner: root
    group: root
    mode: '0644'
  tags:
  - jwt
  - logging
- name: "Проверка JWT конфигурации в slurm.conf"
  lineinfile:
    path: /etc/slurm/slurm.conf
    regexp: '^AuthAltTypes='
    line: 'AuthAltTypes=auth/jwt'
    state: present
    backup: true
  notify: restart slurmctld
  tags:
  - jwt
  - config
- name: "Добавление JWT параметров в slurm.conf"
  lineinfile:
    path: /etc/slurm/slurm.conf
    regexp: '^AuthAltParameters='
    line: 'AuthAltParameters=jwt_key={{jwt_options.key_file}}'
    state: present
    backup: true
  notify: restart slurmctld
  tags:
  - jwt
  - config
- name: "Отображение информации о JWT настройке"
  debug:
    msg:
    - "✅ JWT аутентификация настроена"
    - "🔐 Ключ: {{jwt_options.key_file}}"
    - "🔄 JWKS: {{jwt_options.jwks_file}}"
    - "⚙️ Алгоритм: {{jwt_options.algorithm}}"
    - "🛠️ Генератор токенов: /usr/local/bin/slurm_jwt_generator.py"
    - "✔️ Валидатор токенов: /usr/local/bin/slurm_jwt_validator.py"
    - "📖 Примеры: /etc/slurm/jwt_examples.sh"
    - "🧪 Тест генерации: {{'PASSED' if jwt_test_generation.rc == 0 else 'FAILED'}}"
    - "🧪 Тест валидации: {{'PASSED' if jwt_test_validation.rc == 0 else 'FAILED'}}"
  tags:
  - jwt
  - info
- name: "Создание документации по JWT"
  copy:
    dest: /etc/slurm/JWT_README.md
    content: |
      # Slurm JWT Authentication
      ## Overview
      JWT (JSON Web Token) authentication is configured for this Slurm cluster to enable secure API access.
      ## Files
      - `{{jwt_options.key_file}}` - Primary JWT signing key
      - `{{jwt_options.jwks_file}}` - JWKS file for key rotation
      - `/etc/slurm/jwt.conf` - JWT configuration
      ## Tools
      - `/usr/local/bin/slurm_jwt_generator.py` - Generate JWT tokens
      - `/usr/local/bin/slurm_jwt_validator.py` - Validate JWT tokens
      - `/etc/slurm/jwt_examples.sh` - Usage examples
      ## Usage Examples
      ### Generate a token for user 'admin' (1 hour expiry):
      ```bash
      python3 /usr/local/bin/slurm_jwt_generator.py --user admin --expiry 3600
      ```
      ### Use token with scontrol:
      ```bash
      export SLURM_JWT=$(python3 /usr/local/bin/slurm_jwt_generator.py --user admin --expiry 3600)
      scontrol ping
      ```
      ### Use token with slurmrestd:
      ```bash
      TOKEN=$(python3 /usr/local/bin/slurm_jwt_generator.py --user admin --expiry 3600)
      curl -H "X-SLURM-USER-NAME: admin" -H "X-SLURM-USER-TOKEN: $TOKEN" \
           http://{{inventory_hostname}}:{{slurmrestd_options.port}}/slurm/v0.0.42/ping
      ```
      ## Security Notes
      - JWT keys are stored with restricted permissions (600)
      - Only slurm user and slurm-jwt service user have access
      - Tokens have configurable expiry times
      - Use JWKS for key rotation without service restart
      ## Troubleshooting
      - Check `/var/log/slurm/slurmctld.log` for JWT authentication errors
      - Verify key file permissions and ownership
      - Test token generation and validation scripts
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
  tags:
  - jwt
  - documentation
