---
# =============================================================================
# НАСТРОЙКА MYSQL ДЛЯ SLURM ACCOUNTING
# =============================================================================
- name: "Запуск и включение MySQL сервиса"
  systemd:
    name: mysql
    state: started
    enabled: true
    daemon_reload: true
  tags:
  - mysql
  - services
- name: "Ожидание готовности MySQL"
  wait_for:
    port: 3306
    host: "{{database_host}}"
    timeout: 60
    delay: 10
  tags:
  - mysql
- name: "Проверка статуса MySQL"
  command: systemctl is-active mysql
  register: mysql_status
  changed_when: false
  failed_when: mysql_status.rc != 0
  tags:
  - mysql
  - validation
- name: "Настройка root пароля MySQL (при первой установке)"
  mysql_user:
    name: root
    password: "{{mysql_root_password}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  ignore_errors: yes # Может быть уже настроен
  tags:
  - mysql
  - security
- name: "Создание .my.cnf для root пользователя"
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
    backup: true
  tags:
  - mysql
  - config
- name: "Удаление анонимных пользователей MySQL"
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"
  ignore_errors: true
  tags:
  - mysql
  - security
- name: "Удаление тестовой базы данных"
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"
  ignore_errors: true
  tags:
  - mysql
  - security
- name: "Создание конфигурации MySQL для Slurm"
  blockinfile:
    path: /etc/mysql/mysql.conf.d/slurm.cnf
    create: true
    backup: true
    block: |
      # MySQL configuration for Slurm accounting
      [mysqld]
      # Performance tuning for Slurm
      innodb_buffer_pool_size = {{mysql_innodb_buffer_pool_size}}
      innodb_log_file_size = {{mysql_innodb_log_file_size}}
      innodb_flush_log_at_trx_commit = 2
      innodb_file_per_table = 1
      # Connection settings
      max_connections = 1000
      max_allowed_packet = 64M
      # Timeout settings
      wait_timeout = 28800
      interactive_timeout = 28800
      # Query cache (for older MySQL versions)
      query_cache_size = 128M
      query_cache_type = 1
      # Slow query log
      slow_query_log = 1
      slow_query_log_file = /var/log/mysql/mysql-slow.log
      long_query_time = 2
      # Binary logging
      log_bin = /var/log/mysql/mysql-bin.log
      binlog_expire_logs_seconds = 864000  # 10 days
      # Character set
      character_set_server = utf8mb4
      collation_server = utf8mb4_unicode_ci
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SLURM CONFIG"
  notify: restart mysql
  tags:
  - mysql
  - config
- name: "Перезапуск MySQL с новой конфигурацией"
  systemd:
    name: mysql
    state: restarted
  tags:
  - mysql
  - restart
- name: "Ожидание готовности MySQL после перезапуска"
  wait_for:
    port: 3306
    host: "{{database_host}}"
    timeout: 60
    delay: 5
  tags:
  - mysql
- name: "Создание базы данных для Slurm accounting"
  mysql_db:
    name: "{{database_name}}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_user: root
    login_password: "{{mysql_root_password}}"
  tags:
  - mysql
  - database
- name: "Создание пользователя базы данных для Slurm"
  mysql_user:
    name: "{{database_user}}"
    password: "{{database_password}}"
    priv: "{{database_name}}.*:ALL"
    host: "{{item}}"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"
  loop:
  - localhost
  - "{{inventory_hostname}}"
  - "{{ansible_default_ipv4.address}}"
  tags:
  - mysql
  - database
  - users
- name: "Предоставление дополнительных прав пользователю Slurm"
  mysql_user:
    name: "{{database_user}}"
    priv: "information_schema.*:SELECT"
    append_privs: true
    host: localhost
    login_user: root
    login_password: "{{mysql_root_password}}"
  tags:
  - mysql
  - database
  - users
- name: "Создание скрипта для резервного копирования БД"
  template:
    src: mysql_backup.sh.j2
    dest: /usr/local/bin/slurm_mysql_backup.sh
    owner: root
    group: root
    mode: '0755'
  when: backup_enabled | bool
  tags:
  - mysql
  - backup
- name: "Настройка cron для резервного копирования"
  cron:
    name: "Slurm MySQL backup"
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/slurm_mysql_backup.sh"
    user: root
    state: present
  when: backup_enabled | bool
  tags:
  - mysql
  - backup
  - cron
- name: "Проверка соединения с базой данных"
  mysql_db:
    name: "{{database_name}}"
    state: present
    login_user: "{{database_user}}"
    login_password: "{{database_password}}"
    login_host: "{{database_host}}"
  tags:
  - mysql
  - validation
- name: "Тестирование производительности MySQL"
  shell: |
    mysql -u{{database_user}} -p{{database_password}} -h{{database_host}} {{database_name}} -e "
    SELECT
        @@version as mysql_version,
        @@innodb_buffer_pool_size as buffer_pool_size,
        @@max_connections as max_connections,
        @@character_set_server as charset,
        @@collation_server as collation;
    "
  register: mysql_config_check
  changed_when: false
  tags:
  - mysql
  - validation
- name: "Отображение конфигурации MySQL"
  debug:
    var: mysql_config_check.stdout_lines
  tags:
  - mysql
  - info
- name: "Проверка логов MySQL на ошибки"
  shell: "tail -50 /var/log/mysql/error.log | grep -i error || echo 'No errors found'"
  register: mysql_error_check
  changed_when: false
  tags:
  - mysql
  - validation
- name: "Отображение статуса MySQL"
  debug:
    msg:
    - "✅ MySQL сервер запущен и настроен"
    - "📊 База данных: {{database_name}}"
    - "👤 Пользователь: {{database_user}}"
    - "🔧 Конфигурация оптимизирована для Slurm"
    - "💾 Резервное копирование: {{'включено' if backup_enabled else 'отключено'}}"
  tags:
  - mysql
  - info
