---
# =============================================================================
# КОМПИЛЯЦИЯ И УСТАНОВКА SLURM 25.05.1
# =============================================================================

- name: "Создание рабочей директории для сборки"
  file:
    path: "/tmp/slurm-build"
    state: directory
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0755'
  tags:
  - build
  - prepare

- name: "Проверка существования исходников Slurm"
  stat:
    path: "/tmp/slurm-build/slurm-{{slurm_version}}.tar.bz2"
  register: slurm_archive
  tags:
  - build
  - download

- name: "Скачивание исходников Slurm {{slurm_version}}"
  get_url:
    url: "{{slurm_download_url}}"
    dest: "/tmp/slurm-build/slurm-{{slurm_version}}.tar.bz2"
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
    timeout: 300
  when: not slurm_archive.stat.exists
  tags:
  - build
  - download

- name: "Проверка контрольной суммы архива (если доступна)"
  shell: |
    cd /tmp/slurm-build
    echo "Verifying Slurm archive integrity..."
    file slurm-{{slurm_version}}.tar.bz2
    ls -la slurm-{{slurm_version}}.tar.bz2
  register: archive_check
  changed_when: false
  tags:
  - build
  - validation

- name: "Распаковка исходников Slurm"
  unarchive:
    src: "/tmp/slurm-build/slurm-{{slurm_version}}.tar.bz2"
    dest: "/tmp/slurm-build"
    remote_src: true
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    creates: "/tmp/slurm-build/slurm-{{slurm_version}}"
  tags:
  - build
  - extract

- name: "Проверка наличия configure скрипта"
  stat:
    path: "/tmp/slurm-build/slurm-{{slurm_version}}/configure"
  register: configure_script
  failed_when: not configure_script.stat.exists
  tags:
  - build
  - validation

- name: "Построение строки конфигурации для ./configure"
  set_fact:
    configure_options: >-
      --prefix={{slurm_build_options.prefix}} --sysconfdir={{slurm_build_options.sysconfdir}} --enable-pam={{slurm_build_options.enable_pam | ternary('yes', 'no')}} --enable-x11={{slurm_build_options.enable_x11 | ternary('yes', 'no')}} --with-munge={{slurm_build_options.with_munge}} --with-ssl={{slurm_build_options.with_ssl}} --with-hwloc={{slurm_build_options.with_hwloc}} --with-json={{slurm_build_options.with_json}} --with-jwt={{slurm_build_options.with_jwt}} --with-mysql_config={{slurm_build_options.with_mysql_config}} --with-hdf5={{slurm_build_options.with_hdf5}} --enable-slurmrestd={{slurm_build_options.enable_slurmrestd | ternary('yes', 'no')}} --enable-shared={{slurm_build_options.enable_shared | ternary('yes', 'no')}}
  tags:
  - build
  - config

- name: "Отображение опций конфигурации"
  debug:
    msg:
    - "Конфигурация Slurm:"
    - "{{configure_options}}"
  tags:
  - build
  - info

- name: "Конфигурирование сборки Slurm"
  command: >
    ./configure {{configure_options}}
  args:
    chdir: "/tmp/slurm-build/slurm-{{slurm_version}}"
    creates: "/tmp/slurm-build/slurm-{{slurm_version}}/config.log"
  become_user: "{{slurm_user}}"
  register: configure_result
  tags:
  - build
  - configure

- name: "Проверка результатов конфигурации"
  debug:
    var: configure_result.stdout_lines
  when: configure_result.stdout_lines is defined
  tags:
  - build
  - info

- name: "Проверка config.log на ошибки"
  shell: |
    cd /tmp/slurm-build/slurm-{{slurm_version}}
    if [-f config.log]; then
        echo "=== Checking for configuration errors ==="
        grep -i "error\|failed\|not found" config.log | head -10 || echo "No major errors found"
        echo
        echo "=== Configuration summary ==="
        grep -A 20 "Slurm configuration summary:" config.log || echo "Summary not found"
    fi
  register: config_check
  changed_when: false
  tags:
  - build
  - validation

- name: "Отображение проверки конфигурации"
  debug:
    var: config_check.stdout_lines
  tags:
  - build
  - info

- name: "Компиляция Slurm (это может занять 10-15 минут)"
  command: make -j{{ansible_processor_vcpus | default(4)}}
  args:
    chdir: "/tmp/slurm-build/slurm-{{slurm_version}}"
    creates: "/tmp/slurm-build/slurm-{{slurm_version}}/src/slurmctld/slurmctld"
  become_user: "{{slurm_user}}"
  register: make_result
  tags:
  - build
  - compile

- name: "Проверка успешности компиляции"
  stat:
    path: "{{item}}"
  register: compiled_binaries
  loop:
  - "/tmp/slurm-build/slurm-{{slurm_version}}/src/slurmctld/slurmctld"
  - "/tmp/slurm-build/slurm-{{slurm_version}}/src/slurmd/slurmd"
  - "/tmp/slurm-build/slurm-{{slurm_version}}/src/slurmdbd/slurmdbd"
  - "/tmp/slurm-build/slurm-{{slurm_version}}/src/slurmrestd/slurmrestd"
  failed_when: not item.stat.exists
  tags:
  - build
  - validation

- name: "Установка Slurm"
  command: make install
  args:
    chdir: "/tmp/slurm-build/slurm-{{slurm_version}}"
    creates: "{{slurm_prefix}}/sbin/slurmctld"
  tags:
  - build
  - install

- name: "Создание символических ссылок для системных бинарей"
  file:
    src: "{{slurm_prefix}}/{{item.src}}"
    dest: "{{item.dest}}"
    state: link
    force: true
  loop:
  - {src: "bin/sinfo", dest: "/usr/local/bin/sinfo"}
  - {src: "bin/squeue", dest: "/usr/local/bin/squeue"}
  - {src: "bin/scancel", dest: "/usr/local/bin/scancel"}
  - {src: "bin/sbatch", dest: "/usr/local/bin/sbatch"}
  - {src: "bin/srun", dest: "/usr/local/bin/srun"}
  - {src: "bin/scontrol", dest: "/usr/local/bin/scontrol"}
  - {src: "bin/sacct", dest: "/usr/local/bin/sacct"}
  - {src: "bin/sacctmgr", dest: "/usr/local/bin/sacctmgr"}
  - {src: "sbin/slurmctld", dest: "/usr/local/sbin/slurmctld"}
  - {src: "sbin/slurmd", dest: "/usr/local/sbin/slurmd"}
  - {src: "sbin/slurmdbd", dest: "/usr/local/sbin/slurmdbd"}
  - {src: "sbin/slurmrestd", dest: "/usr/local/sbin/slurmrestd"}
  tags:
  - build
  - install
  - links

- name: "Настройка библиотечных путей"
  blockinfile:
    path: /etc/ld.so.conf.d/slurm.conf
    create: true
    block: |
      # Slurm library paths
      {{slurm_prefix}}/lib
      {{slurm_prefix}}/lib64
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  notify: ldconfig
  tags:
  - build
  - install
  - libraries

- name: "Обновление кэша динамических библиотек"
  command: ldconfig
  tags:
  - build
  - install
  - libraries

- name: "Создание man pages путей"
  blockinfile:
    path: /etc/manpath.config
    block: |
      # Slurm man pages
      MANPATH_MAP {{slurm_prefix}}/bin {{slurm_prefix}}/share/man
      MANPATH_MAP {{slurm_prefix}}/sbin {{slurm_prefix}}/share/man
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SLURM"
    backup: true
  ignore_errors: yes # Файл может не существовать на некоторых системах
  tags:
  - build
  - install
  - documentation

- name: "Проверка установленной версии Slurm"
  command: "{{slurm_prefix}}/bin/scontrol --version"
  register: slurm_version_check
  changed_when: false
  tags:
  - build
  - validation

- name: "Создание информационного файла о сборке"
  copy:
    dest: "{{slurm_prefix}}/BUILD_INFO"
    content: |
      Slurm Build Information
      ======================

      Version: {{slurm_version}}
      Built on: {{ansible_date_time.iso8601}}
      Built by: Ansible (slurm-hpc-deployment)
      Hostname: {{inventory_hostname}}

      Configure options:
      {{configure_options}}

      Build environment:
      - OS: {{ansible_distribution}} {{ansible_distribution_version}}
      - Kernel: {{ansible_kernel}}
      - CPU: {{ansible_processor_vcpus}} cores
      - Memory: {{ansible_memtotal_mb}}MB

      Installed components:
      {% for binary in compiled_binaries.results %}
      - {{binary.item | basename}}: {{'OK' if binary.stat.exists else 'MISSING'}}
      {% endfor %}
    owner: root
    group: root
    mode: '0644'
  tags:
  - build
  - install
  - documentation

- name: "Очистка временных файлов сборки"
  file:
    path: "/tmp/slurm-build"
    state: absent
  when: cleanup_build_files | default(true)
  tags:
  - build
  - cleanup

- name: "Отображение результатов сборки"
  debug:
    msg:
    - "✅ Slurm {{slurm_version}} успешно скомпилирован и установлен"
    - "📁 Префикс: {{slurm_prefix}}"
    - "🔧 Версия: {{slurm_version_check.stdout}}"
    - "🔗 Символические ссылки созданы в /usr/local/"
    - "📚 Библиотеки настроены в /etc/ld.so.conf.d/"
    - "📖 Man pages доступны"
  tags:
  - build
  - info
