---
# =============================================================================
# НАСТРОЙКА SLURM CONTROLLER (SLURMCTLD)
# =============================================================================

- name: "Создание основного конфигурационного файла slurm.conf"
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
    backup: true
  notify: restart slurmctld
  tags:
    - slurmctld
    - config

- name: "Создание конфигурации cgroups"
  template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
    backup: true
  notify: restart slurmctld
  tags:
    - slurmctld
    - cgroups
    - config

- name: "Создание файла allowed devices для cgroups"
  copy:
    dest: /etc/slurm/cgroup_allowed_devices_file.conf
    content: |
      # Allowed devices for Slurm cgroups
      # Device access control for jobs

      # Basic devices
      /dev/null rwm
      /dev/zero rwm
      /dev/full rwm
      /dev/random rwm
      /dev/urandom rwm
      /dev/pts/* rwm
      /dev/ptmx rwm
      /dev/tty rwm
      /dev/console rwm

      # GPU devices (NVIDIA)
      /dev/nvidia* rwm
      /dev/nvidiactl rwm
      /dev/nvidia-uvm rwm
      /dev/nvidia-uvm-tools rwm
      /dev/nvidia-modeset rwm

      # InfiniBand devices
      /dev/infiniband/* rwm
      /dev/rdma_cm rwm

      # Additional devices as needed
      # Add custom device access rules here
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
  tags:
    - slurmctld
    - cgroups
    - config

- name: "Создание конфигурации GRES (GPU Resources)"
  template:
    src: gres.conf.j2
    dest: /etc/slurm/gres.conf
    owner: "{{slurm_user}}"
    group: "{{slurm_group}}"
    mode: '0644'
    backup: true
  notify: restart slurmctld
  tags:
    - slurmctld
    - gres
    - config

- name: "Создание systemd unit файла для slurmctld"
  template:
    src: slurmctld.service.j2
    dest: /etc/systemd/system/slurmctld.service
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - reload systemd
    - restart slurmctld
  tags:
    - slurmctld
    - systemd

- name: "Создание environment файла для slurmctld"
  copy:
    dest: /etc/systemd/system/slurmctld.service.d/environment.conf
    content: |
      [Service]
      Environment="SLURM_CONF=/etc/slurm/slurm.conf"
      Environment="MUNGE_SOCKET=/var/run/munge/munge.socket.2"
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart slurmctld
  tags:
    - slurmctld
    - systemd

- name: "Проверка синтаксиса конфигурации slurm.conf"
  command: "{{slurm_prefix}}/sbin/slurmctld -D -v"
  register: slurmctld_syntax_check
  failed_when:
    - slurmctld_syntax_check.rc != 0
    - "'usage:' not in slurmctld_syntax_check.stderr"
  changed_when: false
  tags:
    - slurmctld
    - validation

- name: "Создание скрипта prolog"
  template:
    src: prolog.sh.j2
    dest: /etc/slurm/prolog.sh
    owner: root
    group: root
    mode: '0755'
    backup: true
  tags:
    - slurmctld
    - prolog
    - config

- name: "Создание скрипта epilog"
  template:
    src: epilog.sh.j2
    dest: /etc/slurm/epilog.sh
    owner: root
    group: root
    mode: '0755'
    backup: true
  tags:
    - slurmctld
    - epilog
    - config

- name: "Создание конфигурации логирования для slurmctld"
  copy:
    dest: /etc/logrotate.d/slurmctld
    content: |
      {{slurm_log_dir}}/slurmctld.log {
          daily
          missingok
          rotate 14
          compress
          delaycompress
          notifempty
          create 0640 {{slurm_user}} {{slurm_group}}
          postrotate
              /bin/systemctl reload slurmctld 2>/dev/null || true
          endscript
    }

      {{slurm_log_dir}}/sched.log {
          daily
          missingok
          rotate 7
          compress
          delaycompress
          notifempty
          create 0640 {{slurm_user}} {{slurm_group}}
          postrotate
              /bin/systemctl reload slurmctld 2>/dev/null || true
          endscript
    }
    owner: root
    group: root
    mode: '0644'
  tags:
    - slurmctld
    - logging

- name: "Перезагрузка systemd daemon"
  systemd:
    daemon_reload: true
  tags:
    - slurmctld
    - systemd

- name: "Запуск и включение slurmctld сервиса"
  systemd:
    name: slurmctld
    state: started
    enabled: true
    daemon_reload: true
  tags:
    - slurmctld
    - services

- name: "Ожидание запуска slurmctld"
  wait_for:
    path: "{{slurm_run_dir}}/slurmctld.pid"
    timeout: 120
    delay: 5
  tags:
    - slurmctld
    - services

- name: "Проверка статуса slurmctld"
  systemd:
    name: slurmctld
  register: slurmctld_status
  tags:
    - slurmctld
    - validation

- name: "Проверка работы команд Slurm"
  command: "{{item}}"
  register: slurm_commands_check
  failed_when: false
  changed_when: false
  loop:
    - "{{slurm_prefix}}/bin/scontrol ping"
    - "{{slurm_prefix}}/bin/sinfo"
    - "{{slurm_prefix}}/bin/squeue"
  tags:
    - slurmctld
    - validation

- name: "Проверка логов slurmctld на ошибки"
  shell: |
    if [-f {{slurm_log_dir}}/slurmctld.log]; then
        tail -50 {{slurm_log_dir}}/slurmctld.log | grep -i "error\|fatal\|fail" | head -10 || echo "No errors found"
    else
        echo "Log file not found"
    fi
  register: slurmctld_log_check
  changed_when: false
  tags:
    - slurmctld
    - validation

- name: "Отображение статуса slurmctld"
  debug:
    msg:
      - "✅ slurmctld настроен и запущен"
      - "📁 Конфигурация: /etc/slurm/slurm.conf"
      - "📝 Логи: {{slurm_log_dir}}/slurmctld.log"
      - "🔄 Статус сервиса: {{slurmctld_status.status.ActiveState}}"
      - "🏗️ Кластер: {{slurmctld_options.cluster_name}}"
      - "🔍 Команды работают: {{slurm_commands_check.results | selectattr('rc', 'equalto', 0) | list | length}}/{{slurm_commands_check.results | length}}"
  tags:
    - slurmctld
    - info

- name: "Отображение результатов проверок"
  debug:
    msg:
      - "📋 Проверки команд:"
{% for result in slurm_commands_check.results %}
      - "  {{result.cmd[0] | basename}}: {{'OK' if result.rc == 0 else 'FAILED'}}"
{% endfor %}
      - "📋 Логи: {{slurmctld_log_check.stdout_lines | default(['Нет ошибок'])}}"
  tags:
    - slurmctld
    - info