---
# =============================================================================
# SLURM MASTER ROLE - MAIN TASKS
# =============================================================================

- name: "Загрузка переменных для Ubuntu 24.04"
  include_vars: "ubuntu-24.04.yml"
  when:
  - ansible_distribution == "Ubuntu"
  - ansible_distribution_version is version("24.04", ">=")
  tags: [always]

- name: "Установка и настройка пакетов"
  include_tasks: packages.yml
  tags: [packages]

- name: "Настройка базы данных MySQL"
  include_tasks: mysql.yml
  when:
  - slurm_enable_slurmdbd | default(true)
  - ansible_distribution == "Ubuntu"
  - ansible_distribution_version is version("24.04", ">=")
  tags: [mysql, database]

- name: "Сборка Slurm из исходного кода"
  include_tasks: build_slurm.yml
  tags: [build, slurm]

- name: "Настройка slurmdbd"
  include_tasks: configure_slurmdbd.yml
  when: slurm_enable_slurmdbd | default(true)
  tags: [slurmdbd, database]

- name: "Настройка slurmctld"
  include_tasks: configure_slurmctld.yml
  tags: [slurmctld, controller]

- name: "Настройка JWT аутентификации"
  include_tasks: configure_jwt.yml
  when: slurm_enable_jwt_auth | default(false)
  tags: [jwt, auth]

- name: "Настройка REST API"
  include_tasks: configure_slurmrestd.yml
  when: slurm_enable_rest_api | default(false)
  tags: [rest-api, slurmrestd]

- name: "Управление сервисами"
  include_tasks: services.yml
  tags: [services]

- name: "Инициализация кластера"
  include_tasks: cluster_init.yml
  when: slurm_initialize_cluster | default(true)
  tags: [cluster-init]

- name: "Валидация установки"
  include_tasks: validation.yml
  when: slurm_run_validation | default(true)
  tags: [validation]

- name: "Настройка резервного копирования"
  include_tasks: backup.yml
  when:
  - slurm_enable_backup | default(true)
  - slurm_configure_backup | default(true)
  tags: [backup]
