---
# =============================================================================
# ОБЩИЕ ПЕРЕМЕННЫЕ ДЛЯ БАЗОВОЙ НАСТРОЙКИ СИСТЕМЫ
# =============================================================================

# Пользователь и группа Slurm
slurm_user: "slurm"
slurm_group: "slurm"
slurm_uid: 981
slurm_gid: 981

# Пользователь и группа MUNGE
munge_user: "munge"
munge_group: "munge"
munge_uid: 982
munge_gid: 982

# Базовые директории
slurm_prefix: "/opt/slurm"
slurm_spool_dir: "/var/spool/slurm"
slurm_log_dir: "/var/log/slurm"
slurm_run_dir: "/var/run/slurm"
slurm_lib_dir: "/var/lib/slurm"

# Директории MUNGE
munge_prefix: "/usr"
munge_conf_dir: "/etc/munge"
munge_log_dir: "/var/log/munge"
munge_run_dir: "/var/run/munge"
munge_lib_dir: "/var/lib/munge"

# Системные настройки
timezone: "UTC"
locale: "en_US.UTF-8"

# Обновление системы
update_system_packages: true
reboot_after_kernel_update: false

# Базовые пакеты для всех нод
base_packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - tree
  - unzip
  - rsync
  - psmisc
  - lsof
  - strace
  - tcpdump
  - net-tools
  - bind9-utils
  - iputils-ping
  - openssh-client
  - ca-certificates
  - software-properties-common
  - apt-transport-https
  - gnupg
  - lsb-release

# Пакеты для разработки и компиляции
build_packages:
  - build-essential
  - autoconf
  - automake
  - libtool
  - pkg-config
  - cmake
  - ninja-build
  - gcc
  - g++
  - gfortran
  - make
  - patch
  - bison
  - flex

# Библиотеки разработки
dev_libraries:
  - libc6-dev
  - libssl-dev
  - libffi-dev
  - libxml2-dev
  - libxslt1-dev
  - libcurl4-openssl-dev
  - libevent-dev
  - libreadline-dev
  - libncurses5-dev
  - libpam0g-dev
  - libdbus-1-dev
  - libhwloc-dev
  - libnuma-dev
  - libcgroup-dev
  - libjson-c-dev
  - libyaml-dev
  - libhttp-parser-dev
  - libjwt-dev
  - zlib1g-dev

# Python пакеты
python_packages:
  - python3
  - python3-dev
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - python3-venv
  - python3-distutils

# Системные сервисы
system_services:
  enabled:
    - ssh
    - systemd-timesyncd
    - rsyslog
  disabled:
    - ufw
    - apparmor
    - snapd

# NTP настройки
ntp_servers:
  - "0.ubuntu.pool.ntp.org"
  - "1.ubuntu.pool.ntp.org"
  - "2.ubuntu.pool.ntp.org"
  - "3.ubuntu.pool.ntp.org"

# Sysctl настройки для производительности
sysctl_settings:
  # Сетевые настройки
  "net.core.rmem_max": "134217728"
  "net.core.wmem_max": "134217728"
  "net.core.rmem_default": "8388608"
  "net.core.wmem_default": "8388608"
  "net.core.netdev_max_backlog": "5000"
  "net.ipv4.tcp_rmem": "4096 65536 134217728"
  "net.ipv4.tcp_wmem": "4096 65536 134217728"
  "net.ipv4.tcp_congestion_control": "bbr"
  
  # Файловая система
  "fs.file-max": "2097152"
  "fs.nr_open": "2097152"
  
  # Виртуальная память
  "vm.swappiness": "1"
  "vm.dirty_ratio": "3"
  "vm.dirty_background_ratio": "1"

# Limits настройки
limits_settings:
  - domain: "*"
    type: "soft"
    item: "nofile"
    value: "65536"
  - domain: "*"
    type: "hard"
    item: "nofile"
    value: "131072"
  - domain: "*"
    type: "soft"
    item: "nproc"
    value: "32768"
  - domain: "*"
    type: "hard"
    item: "nproc"
    value: "65536"

# Логирование
log_level: "info"
enable_debug_logging: false

# Дополнительные репозитории (если необходимо)
additional_repositories: []

# Переменные окружения для всех пользователей
global_environment:
  PATH: "/opt/slurm/bin:/opt/slurm/sbin:$PATH"
  LD_LIBRARY_PATH: "/opt/slurm/lib:/opt/slurm/lib64:$LD_LIBRARY_PATH"
  MANPATH: "/opt/slurm/share/man:$MANPATH"