---
# =============================================================================
# УСТАНОВКА ПАКЕТОВ ДЛЯ SLURM MASTER
# =============================================================================

- name: "Обновление кэша пакетов"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
  - packages

- name: "Установка пакетов для Ubuntu 24.04"
  package:
    name: "{{ item }}"
    state: present
  loop:
  - libhttpparser-dev
  - python3.12-dev
  - python3.12-pip
  when:
  - ansible_os_family == "Debian"
  - ansible_distribution_version is version('24.04', '>=')

- name: "Установка MySQL Server и клиента"
  apt:
    name:
    - mysql-server
    - mysql-client
    - mysql-common
    - libmysqlclient-dev
    - python3-mysqldb
    - python3-pymysql
    state: present
    install_recommends: no
  tags:
  - packages
  - mysql

- name: "Установка MUNGE для аутентификации"
  apt:
    name:
    - munge
    - libmunge-dev
    - libmunge2
    state: present
    install_recommends: no
  tags:
  - packages
  - munge

- name: "Установка библиотек для JWT поддержки"
  apt:
    name:
    - libjwt-dev
    - libjwt0
    - libjson-c-dev
    - libjson-c5
    state: present
    install_recommends: no
  tags:
  - packages
  - jwt

- name: "Установка библиотек для Slurm"
  apt:
    name:
    # Основные библиотеки
    - libssl-dev
    - libpam0g-dev
    - libdbus-1-dev
    - libreadline-dev
    - libncurses5-dev
    - libevent-dev
    - libcurl4-openssl-dev
    - libhttpparser-dev
    - libyaml-dev

    # HWLOC для топологии
    - libhwloc-dev
    - hwloc
    - libnuma-dev

    # HDF5 для профилирования
    - libhdf5-dev
    - hdf5-tools

    # Cgroups
    - libcgroup-dev
    - cgroup-tools

    # Дополнительные утилиты
    - mailutils
    - chrony
    - logrotate
    state: present
    install_recommends: no
  tags:
  - packages
  - libraries

- name: "Установка дополнительных инструментов разработки"
  apt:
    name:
    - git
    - wget
    - curl
    - bzip2
    - tar
    - gzip
    - unzip
    - patch
    - pkgconf
    - rpm2cpio
    - alien
    state: present
    install_recommends: no
  tags:
  - packages
  - tools

- name: "Установка Python пакетов для автоматизации"
  pip:
    name:
    - pexpect
    - pymysql
    - cryptography
    - pyjwt
    - requests
    - pyyaml
    state: present
    executable: pip3
  tags:
  - packages
  - python

- name: "Проверка установки критически важных пакетов"
  package_facts:
    manager: "auto"

- name: "Валидация установленных пакетов"
  assert:
    that:
    - "'mysql-server' in ansible_facts.packages"
    - "'libmunge-dev' in ansible_facts.packages"
    - "'libjwt-dev' in ansible_facts.packages"
    - "'libssl-dev' in ansible_facts.packages"
    - "'libhwloc-dev' in ansible_facts.packages"
    fail_msg: "Не все критически важные пакеты установлены"
    success_msg: "Все необходимые пакеты установлены"
  tags:
  - packages
  - validation

- name: "Проверка доступности команд"
  command: "which {{ item }}"
  register: command_check
  failed_when: command_check.rc != 0
  changed_when: false
  loop:
  - mysql
  - mysqld
  - munge
  - munged
  - pkg-config
  - hwloc-info
  tags:
  - packages
  - validation

- name: "Отображение версий установленных компонентов"
  shell: |
    echo "MySQL: $(mysql --version)"
    echo "MUNGE: $(munge --version 2>&1 | head -1)"
    echo "HWLOC: $(hwloc-info --version)"
    echo "OpenSSL: $(openssl version)"
  register: versions_info
  changed_when: false
  tags:
  - packages
  - info

- name: "Вывод информации о версиях"
  debug:
    var: versions_info.stdout_lines
  tags:
  - packages
  - info
