---
# =============================================================================
# ОБРАБОТЧИКИ СОБЫТИЙ ДЛЯ РОЛИ COMMON
# =============================================================================

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload systemd
  systemd:
    daemon_reload: yes
  tags:
  - handlers

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  tags:
  - handlers

- name: reload sysctl
  command: sysctl --system
  tags:
  - handlers

- name: restart networking
  systemd:
    name: networking
    state: restarted
  tags:
  - handlers

- name: update initramfs
  command: update-initramfs -u
  tags:
  - handlers
