---
# =============================================================================
# ПЕРЕМЕННЫЕ РОЛИ SLURM_MASTER
# =============================================================================

# Версии компонентов
slurm_version: "25.05.1"
slurm_download_url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"
munge_version: "0.5.16"
hwloc_version: "2.11.0"

# Конфигурация компиляции Slurm
slurm_build_options:
  prefix: "{{ slurm_prefix }}"
  sysconfdir: "/etc/slurm"
  enable_pam: true
  enable_x11: true
  with_munge: "/usr"
  with_ssl: "/usr"
  with_hwloc: "/usr"
  with_json: "/usr"
  with_jwt: "/usr"
  with_mysql_config: "/usr/bin/mysql_config"
  with_hdf5: "/usr"
  enable_slurmrestd: true
  enable_shared: true

# База данных
database_type: "mysql"
database_name: "slurm_acct_db"
database_user: "slurm"
database_password: "slurm_db_password_2024"
database_host: "localhost"
database_port: 3306

# MySQL настройки
mysql_root_password: "mysql_root_password_2024"
mysql_innodb_buffer_pool_size: "1G"
mysql_innodb_log_file_size: "256M"

# Конфигурация slurmctld
slurmctld_options:
  cluster_name: "{{ cluster_name | default('hpc-cluster') }}"
  control_machine: "{{ inventory_hostname }}"
  backup_controller: ""
  slurm_user: "{{ slurm_user }}"
  slurm_uid: "{{ slurm_uid }}"
  slurmdbd_host: "{{ inventory_hostname }}"
  state_save_location: "{{ slurm_lib_dir }}/ctld"
  spool_dir: "{{ slurm_spool_dir }}/ctld"
  log_file: "{{ slurm_log_dir }}/slurmctld.log"
  pid_file: "{{ slurm_run_dir }}/slurmctld.pid"

  # Планировщик
  scheduler_type: "sched/backfill"
  select_type: "select/cons_tres"
  select_type_parameters: "CR_Core_Memory"

  # Таймауты
  slurmd_timeout: 300
  inactive_limit: 0
  min_job_age: 300
  kill_wait: 30
  complete_wait: 0

  # Производительность
  max_job_count: 1000000
  max_array_size: 1000000
  max_step_count: 40000
  max_tasks_per_node: 512

  # Аутентификация
  auth_type: "auth/munge"
  auth_alt_types: "auth/jwt"
  cred_type: "cred/munge"

  # Сеть и топология
  tree_width: 16
  switch_type: "switch/generic"
  topology_plugin: "topology/tree"

  # Логирование
  slurmctld_debug: 3
  slurmctld_log_file: "{{ slurm_log_dir }}/slurmctld.log"
  slurm_sched_log_file: "{{ slurm_log_dir }}/sched.log"
  slurm_sched_log_level: 1

# Конфигурация slurmdbd
slurmdbd_options:
  archive_events: "yes"
  archive_jobs: "yes"
  archive_steps: "no"
  archive_suspend: "no"
  archive_txn: "no"
  archive_usage: "no"
  auth_type: "auth/munge"
  auth_alt_types: "auth/jwt"
  debug_level: 3
  log_file: "{{ slurm_log_dir }}/slurmdbd.log"
  pid_file: "{{ slurm_run_dir }}/slurmdbd.pid"
  slurm_user: "{{ slurm_user }}"
  storage_type: "accounting_storage/mysql"
  storage_host: "{{ database_host }}"
  storage_port: "{{ database_port }}"
  storage_user: "{{ database_user }}"
  storage_pass: "{{ database_password }}"
  storage_loc: "{{ database_name }}"

  # Производительность БД
  commit_delay: 10
  purge_event_after: "1month"
  purge_job_after: "12month"
  purge_step_after: "1month"
  purge_suspend_after: "1month"
  purge_txn_after: "12month"
  purge_usage_after: "24month"

# JWT настройки
jwt_options:
  enabled: true
  key_file: "/etc/slurm/jwt.key"
  jwks_file: "/etc/slurm/slurm.jwks"
  algorithm: "HS256"

# slurmrestd настройки
slurmrestd_options:
  enabled: true
  host: "0.0.0.0"
  port: 6820
  auth_type: "rest_auth/jwt"
  openapi_version: "v0.0.42"

# Сервисы для запуска на master ноде
slurm_master_services:
- slurmctld
- slurmdbd
- slurmrestd

# Порты для firewall
slurm_master_ports:
- "6817/tcp" # slurmctld
- "6819/tcp" # slurmdbd  
- "6820/tcp" # slurmrestd

# Cgroups настройки
cgroups_config:
  cgroup_automount: "yes"
  cgroup_release_agent_dir: "/etc/slurm/cgroup"
  constrain_cores: "yes"
  constrain_ram_space: "yes"
  constrain_swap_space: "no"
  constrain_devices: "yes"
  constrain_kmem_space: "no"
  memory_swappiness: 1
  allowed_devices_file: "/etc/slurm/cgroup_allowed_devices_file.conf"

# Прочие настройки
slurm_accounting_storage_enforce: "associations,limits,qos"
slurm_job_accounting_gather_type: "jobacct_gather/linux"
slurm_job_accounting_gather_frequency: "30"

# Резервное копирование
backup_enabled: true
backup_schedule: "0 2 * * *" # Каждый день в 2:00
backup_retention_days: 30
backup_location: "/shared/backups/slurm"

# Логирование
enable_debug_logging: false
log_rotation_enabled: true
log_max_size: "100M"
log_retention_days: 14
