---
# =============================================================================
# СОЗДАНИЕ ДИРЕКТОРИЙ ДЛЯ SLURM И MUNGE
# =============================================================================

- name: "Создание базовых директорий Slurm"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    recurse: yes
  loop:
  # Основные директории Slurm
  - { path: "{{ slurm_prefix }}", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/bin", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/sbin", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/lib", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/lib64", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/include", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/share", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/share/man", owner: "root", group: "root", mode: "0755" }
  - { path: "{{ slurm_prefix }}/etc", owner: "root", group: "root", mode: "0755" }

  # Конфигурационные директории
  - { path: "/etc/slurm", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }
  - { path: "/etc/slurm/plugstack.conf.d", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }

  # Рабочие директории Slurm
  - { path: "{{ slurm_spool_dir }}", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }
  - { path: "{{ slurm_spool_dir }}/ctld", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }
  - { path: "{{ slurm_spool_dir }}/d", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }
  - { path: "{{ slurm_lib_dir }}", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }
  - { path: "{{ slurm_run_dir }}", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }

  # Логи Slurm
  - { path: "{{ slurm_log_dir }}", owner: "{{ slurm_user }}", group: "{{ slurm_group }}", mode: "0755" }

  # Системные директории
  - { path: "/usr/lib/slurm", owner: "root", group: "root", mode: "0755" }
  - { path: "/usr/share/slurm", owner: "root", group: "root", mode: "0755" }
  tags:
  - directories
  - slurm

- name: "Создание директорий для MUNGE"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: yes
  loop:
  - { path: "{{ munge_conf_dir }}", owner: "{{ munge_user }}", group: "{{ munge_group }}", mode: "0700" }
  - { path: "{{ munge_log_dir }}", owner: "{{ munge_user }}", group: "{{ munge_group }}", mode: "0755" }
  - { path: "{{ munge_run_dir }}", owner: "{{ munge_user }}", group: "{{ munge_group }}", mode: "0755" }
  - { path: "{{ munge_lib_dir }}", owner: "{{ munge_user }}", group: "{{ munge_group }}", mode: "0711" }
  tags:
  - directories
  - munge

- name: "Создание директорий для логов systemd сервисов"
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "systemd-journal"
    mode: "0755"
  loop:
  - "/var/log/journal"
  - "/etc/systemd/system"
  - "/etc/systemd/system/slurmd.service.d"
  - "/etc/systemd/system/slurmctld.service.d"
  - "/etc/systemd/system/slurmdbd.service.d"
  tags:
  - directories
  - systemd

- name: "Создание временных директорий для сборки"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: "0755"
  loop:
  - "/tmp/slurm-build"
  - "/tmp/munge-build"
  - "/var/tmp/slurm"
  tags:
  - directories
  - build

- name: "Создание директорий для NFS монтирования"
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
  - "/shared"
  - "/shared/home"
  - "/shared/sw"
  - "/shared/data"
  tags:
  - directories
  - nfs

- name: "Проверка созданных директорий"
  stat:
    path: "{{ item }}"
  register: directory_check
  loop:
  - "{{ slurm_prefix }}"
  - "/etc/slurm"
  - "{{ slurm_spool_dir }}"
  - "{{ slurm_log_dir }}"
  - "{{ munge_conf_dir }}"
  - "{{ munge_lib_dir }}"
  tags:
  - directories
  - validation

- name: "Отображение информации о созданных директориях"
  debug:
    msg: "Директория {{ item.item }} создана: {{ item.stat.exists }}"
  loop: "{{ directory_check.results }}"
  tags:
  - directories
  - info
