---
# =============================================================================
# НАСТРОЙКА ОКРУЖЕНИЯ И ПЕРЕМЕННЫХ
# =============================================================================

- name: "Создание глобального профиля для Slurm"
  copy:
    dest: /etc/profile.d/slurm.sh
    content: |
      # Slurm HPC environment
      export PATH="/opt/slurm/bin:/opt/slurm/sbin:$PATH"
      export LD_LIBRARY_PATH="/opt/slurm/lib:/opt/slurm/lib64:$LD_LIBRARY_PATH"
      export MANPATH="/opt/slurm/share/man:$MANPATH"
      export PKG_CONFIG_PATH="/opt/slurm/lib/pkgconfig:/opt/slurm/lib64/pkgconfig:$PKG_CONFIG_PATH"

      # Slurm useful aliases
      alias si='sinfo -o "%20N %10T %4c %8z %15C %8O %8m %18f %19E"'
      alias sq='squeue -o "%.7i %.12j %.8u %.8T %.10M %.9l %.6D %R"'
      alias sa='sacct --format=JobID,JobName,User,State,Start,End,Elapsed,CPUTime,ReqMem,MaxRSS'
      alias sj='scontrol show job'
      alias sn='scontrol show node'
      alias sp='scontrol show partition'
    owner: root
    group: root
    mode: '0644'
  tags:
  - environment
  - profile

- name: "Создание модульной системы окружения"
  copy:
    dest: /etc/profile.d/modules.sh
    content: |
      # Environment modules initialization
      if [ -d /opt/modules ]; then
          export MODULEPATH="/opt/modules/modulefiles:$MODULEPATH"
          if [ -f /opt/modules/init/bash ]; then
              source /opt/modules/init/bash
          fi
      fi
    owner: root
    group: root
    mode: '0644'
  tags:
  - environment
  - modules

- name: "Настройка bashrc для пользователя saadmin"
  blockinfile:
    path: "/home/saadmin/.bashrc"
    create: yes
    owner: saadmin
    group: saadmin
    mode: '0644'
    block: |
      # Slurm HPC environment
      export PATH="/opt/slurm/bin:/opt/slurm/sbin:$PATH"
      export LD_LIBRARY_PATH="/opt/slurm/lib:/opt/slurm/lib64:$LD_LIBRARY_PATH"
      export MANPATH="/opt/slurm/share/man:$MANPATH"

      # HPC useful settings
      export HISTSIZE=10000
      export HISTFILESIZE=20000
      export HISTCONTROL=ignoredups:erasedups

      # Slurm aliases
      alias si='sinfo -o "%20N %10T %4c %8z %15C %8O %8m %18f %19E"'
      alias sq='squeue -o "%.7i %.12j %.8u %.8T %.10M %.9l %.6D %R"'
      alias sa='sacct --format=JobID,JobName,User,State,Start,End,Elapsed,CPUTime,ReqMem,MaxRSS'

      # System aliases
      alias ll='ls -alF'
      alias la='ls -A'
      alias l='ls -CF'
      alias grep='grep --color=auto'
      alias ..='cd ..'
      alias ...='cd ../..'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HPC ENVIRONMENT"
  tags:
  - environment
  - user

- name: "Создание глобальной конфигурации vim для HPC"
  copy:
    dest: /etc/vim/vimrc.local
    content: |
      " HPC cluster vim configuration
      syntax on
      set number
      set tabstop=4
      set shiftwidth=4
      set expandtab
      set autoindent
      set smartindent
      set hlsearch
      set incsearch
      set showmatch
      set ruler
      set laststatus=2
      set backspace=indent,eol,start

      " File type specific settings
      autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
      autocmd FileType python setlocal ts=4 sts=4 sw=4 expandtab
      autocmd FileType sh setlocal ts=2 sts=2 sw=2 expandtab
    owner: root
    group: root
    mode: '0644'
  tags:
  - environment
  - editor

- name: "Создание конфигурации tmux для пользователей"
  copy:
    dest: /etc/tmux.conf
    content: |
      # HPC cluster tmux configuration
      set -g default-terminal "screen-256color"
      set -g history-limit 10000
      set -g base-index 1
      setw -g pane-base-index 1

      # Key bindings
      bind | split-window -h
      bind - split-window -v
      bind r source-file ~/.tmux.conf \; display "Reloaded!"

      # Status bar
      set -g status-bg colour235
      set -g status-fg colour255
      set -g status-left '#[fg=green]#H #[fg=yellow]#S'
      set -g status-right '#[fg=yellow]%Y-%m-%d %H:%M'
      set -g status-interval 60

      # Window options
      setw -g window-status-current-format '#[fg=black,bg=green] #I:#W '
      setw -g window-status-format '#[fg=white,bg=colour235] #I:#W '
    owner: root
    group: root
    mode: '0644'
  tags:
  - environment
  - tmux

- name: "Создание скрипта для проверки состояния кластера"
  copy:
    dest: /usr/local/bin/cluster-status
    content: |
      #!/bin/bash
      # Быстрая проверка состояния HPC кластера

      echo "=== HPC Cluster Status ==="
      echo "Time: $(date)"
      echo "Uptime: $(uptime -p)"
      echo

      if command -v sinfo &> /dev/null; then
          echo "=== Slurm Nodes ==="
          sinfo -N -o "%20N %10T %4c %8z %15C %8O %8m"
          echo
          
          echo "=== Slurm Queue ==="
          squeue -o "%.7i %.12j %.8u %.8T %.10M %.9l %.6D %R" | head -20
          echo
      fi

      echo "=== System Load ==="
      echo "CPU: $(nproc) cores"
      echo "Memory: $(free -h | grep Mem | awk '{print $3"/"$2}')"
      echo "Load: $(cat /proc/loadavg | cut -d' ' -f1-3)"
      echo

      if ls /dev/nvidia* &> /dev/null; then
          echo "=== GPU Status ==="
          nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu --format=csv,noheader,nounits | head -8
      fi
    owner: root
    group: root
    mode: '0755'
  tags:
  - environment
  - tools

- name: "Создание MOTD для информации о кластере"
  copy:
    dest: /etc/motd
    content: |
      ================================================================================

         ██╗  ██╗██████╗  ██████╗     ██████╗██╗     ██╗   ██╗███████╗████████╗███████╗██████╗ 
         ██║  ██║██╔══██╗██╔════╝    ██╔════╝██║     ██║   ██║██╔════╝╚══██╔══╝██╔════╝██╔══██╗
         ███████║██████╔╝██║         ██║     ██║     ██║   ██║███████╗   ██║   █████╗  ██████╔╝
         ██╔══██║██╔═══╝ ██║         ██║     ██║     ██║   ██║╚════██║   ██║   ██╔══╝  ██╔══██╗
         ██║  ██║██║     ╚██████╗    ╚██████╗███████╗╚██████╔╝███████║   ██║   ███████╗██║  ██║
         ╚═╝  ╚═╝╚═╝      ╚═════╝     ╚═════╝╚══════╝ ╚═════╝ ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝

      ================================================================================

      Welcome to the HPC Cluster!

      Useful commands:
        cluster-status     - Check cluster status
        si                 - Show node information (sinfo)
        sq                 - Show job queue (squeue)
        sa                 - Show job accounting (sacct)

      Documentation: /shared/docs/
      Support: Create ticket in helpdesk

      ================================================================================
    owner: root
    group: root
    mode: '0644'
  tags:
  - environment
  - motd

- name: "Проверка настроек окружения"
  shell: |
    source /etc/profile.d/slurm.sh
    echo "PATH includes Slurm: $(echo $PATH | grep -o '/opt/slurm')"
    echo "LD_LIBRARY_PATH includes Slurm: $(echo $LD_LIBRARY_PATH | grep -o '/opt/slurm')"
  register: env_check
  changed_when: false
  tags:
  - environment
  - validation

- name: "Отображение результатов проверки окружения"
  debug:
    var: env_check.stdout_lines
  tags:
  - environment
  - info
