---
# =============================================================================
# УСТАНОВКА СИСТЕМНЫХ ПАКЕТОВ
# =============================================================================

- name: "Обновление кэша пакетов apt"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: update_system_packages | bool
  tags:
    - packages

- name: "Установка базовых системных пакетов"
  apt:
    name: "{{ base_packages }}"
    state: present
    install_recommends: no
  tags:
    - packages
    - base

- name: "Установка пакетов для разработки и компиляции"
  apt:
    name: "{{ build_packages }}"
    state: present
    install_recommends: no
  tags:
    - packages
    - build

- name: "Установка библиотек разработки"
  apt:
    name: "{{ dev_libraries }}"
    state: present
    install_recommends: no
  tags:
    - packages
    - dev-libs

- name: "Установка Python пакетов"
  apt:
    name: "{{ python_packages }}"
    state: present
    install_recommends: no
  tags:
    - packages
    - python

- name: "Обновление всех установленных пакетов"
  apt:
    upgrade: safe
    autoremove: yes
    autoclean: yes
  when: update_system_packages | bool
  tags:
    - packages
    - upgrade

- name: "Проверка необходимости перезагрузки после обновления ядра"
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags:
    - packages
    - reboot

- name: "Уведомление о необходимости перезагрузки"
  debug:
    msg: "Система требует перезагрузки после обновления ядра"
  when: 
    - reboot_required_file.stat.exists
    - reboot_after_kernel_update | bool
  tags:
    - packages
    - reboot

- name: "Перезагрузка системы после обновления ядра"
  reboot:
    reboot_timeout: 900  # 15 минут для compute нод
    post_reboot_delay: 30
    test_command: uptime
  when: 
    - reboot_required_file.stat.exists
    - reboot_after_kernel_update | bool
  tags:
    - packages
    - reboot

- name: "Проверка доступности критически важных команд"
  command: "{{ item }}"
  register: command_check
  failed_when: command_check.rc != 0
  changed_when: false
  loop:
    - "gcc --version"
    - "make --version"
    - "python3 --version"
    - "pkg-config --version"
    - "autoconf --version"
  tags:
    - packages
    - validation