---
# =============================================================================
# ОБРАБОТЧИКИ СОБЫТИЙ ДЛЯ РОЛИ SLURM_MASTER
# =============================================================================

- name: restart mysql
  systemd:
    name: mysql
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload mysql
  systemd:
    name: mysql
    state: reloaded
  tags:
  - handlers

- name: restart slurmctld
  systemd:
    name: slurmctld
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload slurmctld
  systemd:
    name: slurmctld
    state: reloaded
  tags:
  - handlers

- name: restart slurmdbd
  systemd:
    name: slurmdbd
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload slurmdbd
  systemd:
    name: slurmdbd
    state: reloaded
  tags:
  - handlers

- name: restart slurmrestd
  systemd:
    name: slurmrestd
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload slurmrestd
  systemd:
    name: slurmrestd
    state: reloaded
  tags:
  - handlers

- name: restart munge
  systemd:
    name: munge
    state: restarted
    daemon_reload: yes
  tags:
  - handlers

- name: reload munge
  systemd:
    name: munge
    state: reloaded
  tags:
  - handlers

- name: ldconfig
  command: ldconfig
  tags:
  - handlers

- name: update mandb
  command: mandb
  ignore_errors: yes
  tags:
  - handlers

- name: reload systemd
  systemd:
    daemon_reload: yes
  tags:
  - handlers

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  tags:
  - handlers

- name: reload logrotate
  command: logrotate -f /etc/logrotate.conf
  ignore_errors: yes
  tags:
  - handlers
