---
# =============================================================================
# ТЕСТОВЫЙ ПЛЕЙБУК ДЛЯ РОЛИ COMMON
# =============================================================================

- name: "Тестирование базовой настройки системы"
  hosts: slurm_cluster
  become: yes
  gather_facts: yes

  vars:
    # Переопределение переменных для тестирования
    timezone: "Europe/Moscow"
    update_system_packages: true
    reboot_after_kernel_update: false
    log_level: "debug"

  pre_tasks:
  - name: "Проверка доступности хостов"
    ping:
    tags: always

  - name: "Отображение целевых хостов"
    debug:
      msg: "Настройка {{ inventory_hostname }} ({{ ansible_default_ipv4.address }})"
    tags: always

  roles:
  - role: common
    tags:
    - common
    - base

  post_tasks:
  - name: "Финальная валидация системы"
    block:
    - name: "Проверка созданных пользователей"
      command: "id {{ item }}"
      register: user_validation
      loop:
      - "{{ slurm_user }}"
      - "{{ munge_user }}"
      changed_when: false

    - name: "Проверка директорий Slurm"
      stat:
        path: "{{ item }}"
      register: dir_validation
      loop:
      - "{{ slurm_prefix }}"
      - "/etc/slurm"
      - "{{ slurm_spool_dir }}"
      - "{{ slurm_log_dir }}"

    - name: "Проверка критически важных команд"
      command: "which {{ item }}"
      register: cmd_validation
      loop:
      - gcc
      - make
      - python3
      - cmake
      changed_when: false

    - name: "Проверка окружения"
      shell: |
        source /etc/profile.d/slurm.sh
        echo $PATH | grep -q '/opt/slurm/bin'
      register: env_validation
      changed_when: false

    - name: "Отображение результатов валидации"
      debug:
        msg:
        - "✅ Пользователи созданы: {{ user_validation.results | map(attribute='stdout') | list }}"
        - "✅ Директории созданы: {{ dir_validation.results | selectattr('stat.exists') | list | length }}/{{ dir_validation.results | list | length }}"
        - "✅ Команды доступны: {{ cmd_validation.results | map(attribute='stdout') | list }}"
        - "✅ Окружение настроено: {{ env_validation.rc == 0 }}"

    rescue:
    - name: "Ошибка валидации"
      debug:
        msg: "❌ Обнаружены ошибки в процессе валидации"
      failed_when: true

    tags:
    - validation
    - always

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЙ ПЛЕЙБУК ДЛЯ ОТЛАДКИ
# =============================================================================

- name: "Сбор информации о системе после настройки"
  hosts: slurm_cluster
  become: yes
  gather_facts: no

  tasks:
  - name: "Сбор системной информации"
    setup:
      gather_subset:
      - 'all'
    register: system_facts

  - name: "Проверка производительности системы"
    shell: |
      echo "=== CPU INFO ==="
      lscpu | grep -E '^(CPU|Model|Architecture|Thread|Core|Socket)'
      echo
      echo "=== MEMORY INFO ==="
      free -h
      echo
      echo "=== DISK INFO ==="
      df -h | grep -E '^(/dev|Filesystem)'
      echo
      echo "=== NETWORK INFO ==="
      ip addr show | grep -E '^[0-9]|inet '
      echo
      echo "=== SLURM ENVIRONMENT ==="
      source /etc/profile.d/slurm.sh && env | grep -E '(PATH|LD_LIBRARY_PATH|MANPATH)' | head -3
    register: system_info

  - name: "Отображение системной информации"
    debug:
      var: system_info.stdout_lines
    tags:
    - info
    - debug
